# Generated by Django 4.0.3 on 2022-03-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteinfo',
            name='Atualizado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='IP',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='Porto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='Velocidade',
            field=models.CharField(max_length=100),
        ),
    ]
